Week01
Altu-Bitu-7/Altu-Bitu-KimSeoYoung pull request #2
Opened 2024-08-29 15:24 UTC by Sarah020202

### 인적사항
학번 : 2277040
이름 : 김서영

### 과제제출
추가 제출 : 1431, 14425, 19636

2024-09-01 06:31 UTC, chae-jpg approved these changes
**[정렬, 맵, 셋 구현 코드리뷰 완료]**
14425(P3) 
서영님 안녕하세요! 코드 리뷰 완료되었습니다👍 
몇 가지 사소한 코멘트 남겼습니다! 
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-09-01 06:31 UTC, chae-jpg commented on BOJ_14425.cpp
> +    int N,M;
P3
알튜비튜에서는 상수를 제외한 변수명에는 소문자 사용을 원칙으로 하고 있습니다! 
n, m으로 변경하면 더 좋을 것 같아요 👍

2024-09-01 06:31 UTC, chae-jpg commented on BOJ_14425.cpp
> +    map <string, bool> m;
탐색에 용이한 자료구조인 맵을 사용해 문제를 잘 해결해주셨네요!

2024-09-02 11:23 UTC, flowing1ife requested changes
[정렬, 맵, 셋 구현 코드리뷰 완료]
1431(P1) 
코드 리뷰 완료하였습니다 !
전체적으로 주석을 추가해서 코드의 가독성을 높이면 더욱 좋을 것 같습니다 ㅎㅎ
몇 가지 사소한 코멘트 남겼으니 확인해주세요 😊
도전문제까지 너무 수고 많으셨습니다 :)

2024-09-02 11:23 UTC, flowing1ife commented on BOJ_1431.cpp
> +    string serial[50];
P1
string이 아닌 vector를 사용해서 n개만큼 초기화해준다면 메모리 측면에서도 효율적이고 훨씬 더 코드가 간결해져요 !

2024-09-02 11:23 UTC, flowing1ife commented on BOJ_1431.cpp
> +    }
P2
sum1 과 sum2가 같은 행위를 반복하고 있어요 ! 따라서 따로 함수화하는 것을 권장드립니다 !
위처럼 시리얼 번호를 구성하는 숫자의 합을 구하는 역할을 하는 코드는 cmp 함수가 아닌 sumNum과 같은 함수로 빼면 좋을 것 같아요 ㅎㅎ

2024-09-02 11:23 UTC, flowing1ife commented on BOJ_1431.cpp
> +bool compare(string a, string b){
P2  
cmp 함수의 경우, 두 인자를 비교하기 때문에 중간에 값이 바뀌지 않도록 상수로 선언하는 것을 권장 드리며 단순히 값을 복사하는 것이 아닌 포인터로 값을 정확히 가져오는 것을 추천드립니다. 

`bool compare(const string& a, const string& b)`

2024-09-17 08:10 UTC, closed without merging