[그리디 알고리즘] 09월24일
Altu-Bitu-7/Altu-Bitu-KimSeoYoung pull request #6
Opened 2024-09-24 09:03 UTC by Sarah020202

### 인적사항
이름 : 김서영
학번 : 2277040

### 과제제출
기존 제출 : 1213, 15662, 17451
추가 제출 :

2024-09-30 13:18 UTC, mons-trev requested changes

2024-09-30 13:18 UTC, mons-trev commented on BOJ_1213.cpp
> +            cout << res[i];
p3. 
출력문은 main 함수에 넣어주는 것이 좋습니다! 함수의 사용 목적이 재사용성이기 때문입니다. main 이 아닌 함수에는 디버깅용으로 종종 출력문을 쓰지만 디버깅용이 아니라면 출력은 함수의 목적을 위해 main 에서 하는 것이 좋습니다 ㅎㅎ

2024-09-30 13:18 UTC, mons-trev commented on BOJ_1213.cpp
> +            alpha[i+'A']--;
p1.
alpha 라는 배열에 'A' 를 0으로 하여 순차적으로 'B' 는 1, 'C' 는 2로 인덱스를 지정해주셨군요! 문자형을 잘 이해하고 사용해주신 것 같습니다👍
다만 여기서 실수를 하신 것 같은데, alpha 의 값을 하나씩 줄일 때 인덱스 접근 방식이 잘못 된 것 같아요ㅎㅎ
이렇게 제출하면 outofbound 런타임 에러가 뜨는데 수정해서 다시 제출해보시길 바랍니다!
이해가 안되는 부분이 있으면 언제든 리뷰어를 호출해 주세요😊

2024-10-01 04:10 UTC, avocado8 requested changes
15662(p1)
서영님 안녕하세요 :3 백준 채점에서 틀렸습니다가 뜨는 코드는 출석 처리되지 않습니다 😢 코멘트 확인하시고 수정 부탁드릴게요~
과제에서 어려운 부분이 생기면 언제든 슬랙 채널에 질문 남겨주세요 🙆‍♀️

2024-10-01 04:10 UTC, avocado8 commented on BOJ_15662.cpp
> +    if (gear_idx < gears->size() - 1 && rotated[gear_idx + 1] == 0) {
p1. gears를 vector<int> 들의 배열로 선언하였기 때문에 size()를 사용할 수 없을 것 같아요~ 우리는 이미 gears의 크기를 알고 있으니 그 변수를 활용하면 될 것 같네요.

2024-10-01 09:10 UTC, merged

2024-10-04 04:15 UTC, kimeunsom reviewed
(17451) 평행우주 문제는 각 단계마다 조건을 만족하는 가능한 적은 속도로 업데이트해나가면서 최적해를 확장해나가는 그리디 문제였습니다 ! 매 단계 가장 적은 속도를 탐욕적으로 선택하면 정답을 구할 수 있었습니다 :) 그리디한 접근법으로 잘 구현해주셨어요 ! 고생 많으셨습니다 ~

(튜터의 개인적 사정으로 코드 리뷰가 늦어진 점 사과드립니다. 코드 리뷰가 너무 늦어져 죄송하지만, 다음부터는 모든 문제가 리뷰된 후에 merge 해주시면 감사하겠습니다 !)

2024-10-04 04:15 UTC, kimeunsom commented on BOJ_17451.cpp
> +            min_speed = (min_speed / speeds[i] + 1) * speeds[i];
최소 속도 이상의 배수를 설정하는 구현이 깔끔하네요 :)

2024-10-04 04:15 UTC, kimeunsom commented on BOJ_17451.cpp
> +    //구현
(p3) 코드의 재사용성을 높이기 위해, 해당 구현 로직을 함수화해보면 어떨까요?